first translation of the tidyr::cms_patient_experience
cienciadedatos/dados pull request #92
Opened 2023-11-12 21:15 UTC by beatrizmilz

#88

2023-11-12 21:54 UTC, beatrizmilz commented
@halian-vilela, se quiser revisar essa tradução, fiz uma v1!

2023-11-14 21:10 UTC, rivaquiroga commented
@beatrizmilz, a workaround could be to put the values inside quotations marks 🤔. We'll need to test if it works!

2023-11-15 00:34 UTC, beatrizmilz commented
Good idea! It worked with the `translate()` function.
```
> translate("cms_patient_experience.yml")
# A tibble: 500 × 5
   organizacao_id organizacao_nome           medida_codigo medida_titulo
   <chr>          <chr>                      <chr>         <chr>        
 1 0446157747     USC CARE MEDICAL GROUP INC CAHPS_GRP_1   Obtenção de …
 2 0446157747     USC CARE MEDICAL GROUP INC CAHPS_GRP_2   O quão bem o…
 3 0446157747     USC CARE MEDICAL GROUP INC CAHPS_GRP_3   CAHPS for MI…
 4 0446157747     USC CARE MEDICAL GROUP INC CAHPS_GRP_5   Promoção e e…
 5 0446157747     USC CARE MEDICAL GROUP INC CAHPS_GRP_8   Equipe do co…
 6 0446157747     USC CARE MEDICAL GROUP INC CAHPS_GRP_12  Administraçã…
 7 0446162697     ASSOCIATION OF UNIVERSITY… CAHPS_GRP_1   Obtenção de …
 8 0446162697     ASSOCIATION OF UNIVERSITY… CAHPS_GRP_2   O quão bem o…
 9 0446162697     ASSOCIATION OF UNIVERSITY… CAHPS_GRP_3   CAHPS for MI…
10 0446162697     ASSOCIATION OF UNIVERSITY… CAHPS_GRP_5   Promoção e e…
# ℹ 490 more rows
# ℹ 1 more variable: taxa_performance <dbl>
# ℹ Use `print(n = ...)` to see more rows
```

2023-11-15 00:35 UTC, beatrizmilz commented
@scopinho Caso queira revisar esse também, é o último que falta para a tradução do capítulo sobre tidyr!

2023-11-15 09:14 UTC, scopinho commented
> @scopinho Caso queira revisar esse também, é o último que falta para a tradução do capítulo sobre tidyr!

Oi @beatrizmilz , pode me colocar que revisareo este também.

2023-11-15 12:17 UTC, scopinho requested changes
@beatrizmilz , revisao feita. Pequeno ajuste no titulo e descrição. Veja se faz sentido pls.

2023-11-15 12:17 UTC, scopinho commented on inst/specs/cms_patient_experience.yml
> +  description: "Contém alguns dados levemente arrumados de 'Prestadores de cuidados paliativos - Dados do provedor', que fornece uma lista de agências de cuidados paliativos junto com alguns dados so
```suggestion
  description: "Contém alguns dados levemente arrumados de 'Prestadores de cuidados paliativos - Dados do provedor', que fornece uma lista de agências de cuidados paliativos intensivos (*hospice*) junto com alguns dados sobre a qualidade do atendimento ao paciente, https://data.cms.gov/provider-data/dataset/252m-zfp9"
```

2023-11-15 12:17 UTC, scopinho commented on inst/specs/cms_patient_experience.yml
> +  title: "Dados dos Centros de Serviços Medicare e Medicaid"
```suggestion
  title: "Dados dos Centros de Serviços de Assistência Médica (*Medicare*) e Medicamentos (*Medicaid*)"
```

2023-11-15 12:24 UTC, beatrizmilz commented
> @beatrizmilz , revisao feita. Pequeno ajuste no titulo e descrição. Veja se faz sentido pls.

Faz sentido sim!

2023-11-15 19:30 UTC, merged