Tradução da base dados_oms2
cienciadedatos/dados pull request #94
Opened 2023-11-12 21:50 UTC by beatrizmilz

2023-11-12 21:53 UTC, beatrizmilz commented
Oi Andrea! Tudo bem?
Estamos traduzindo o livro R4DS, e apareceram novas bases de dados no livro.
Uma delas é a `who2`, derivada da `who`, que você traduziu.
Eu fiz uma primeira versão da tradução, já que é bem similar á `who`.
Você gostaria de fazer a revisão? Considerando que traduziu a `who`.
Abraços!

2023-11-13 17:18 UTC, beatrizmilz commented
@scopinho a base está aqui!

2023-11-14 11:41 UTC, scopinho requested changes
Bea, no who2 observei que as variaveis (new_sp_*) nao existem mais. Deixaram simplesmente como sp_*.
Revisado.

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_m_014:
```suggestion
  sp_m_014:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_m_1524:
```suggestion
  sp_m_1524:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_m_2534:
```suggestion
  sp_m_2534:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_m_3544:
```suggestion
  sp_m_3544:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_m_4554:
```suggestion
  sp_m_4554:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_m_5564:
```suggestion
  sp_m_5564:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_m_65:
```suggestion
  sp_m_65:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_f_014:
```suggestion
  sp_f_014:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_f_1524:
```suggestion
  sp_f_1524:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_f_2534:
```suggestion
  sp_f_2534:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_f_3544:
```suggestion
  sp_f_3544:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_f_4554:
```suggestion
  sp_f_4554:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_f_5564:
```suggestion
  sp_f_5564:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  new_sp_f_65:
```suggestion
  sp_f_65:
```

2023-11-14 11:41 UTC, scopinho commented on inst/specs/who2.yml
> +  description: "Subconjunto de dados do relat\u00f3rio anual de tuberculose da Organiza\u00e7\u00e3o Mundial da Sa\u00fade. A tibble dados_oms2 é uma versão levemente modificada de dados_oms"
```suggestion
  description: "Subconjunto de dados do relat\u00f3rio anual de tuberculose da Organiza\u00e7\u00e3o Mundial da Sa\u00fade. A tibble dados_oms2 é uma versão levemente modificada de dados_oms, ajustando as variaveis para serem mais consistentes, removendo iso2, iso3 e adicionando _ depois do sexo biol\u00f3gico"
```

2023-11-14 21:34 UTC, merged